name: Unit Tests
on:
  pull_request:
    branches:
      - main
      - production

jobs:
  jest-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Node.js Setup
        uses: actions/setup-node@v3
      - name: Install Packages
        run: npm ci
      - name: Run Tests
        run: npm run test
      - name: Update Coverage Badge
        # GitHub actions: default branch variable
        # https://stackoverflow.com/questions/64781462/github-actions-default-branch-variable
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: we-cli/coverage-badge-action@main
