name: Unit Tests
on:
  pull_request:
    branches:
      - main
      - production

jobs:
  jest-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Packages
        run: npm ci
      - name: Run Tests
        run: npm run test
